id: P009553
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16581
  title: གངས་ལྗོངས་དགོན་སྡེའི་སློབ་དེབ་དཔེ་ཚོགས།
  author: ''
  volumes:
    7bcfaf8150fd41609f7f4b63d9c45c64:
      image_group_id: I2PD18456
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
    f4aa1ae9d3c046338db62df007fc2132:
      image_group_id: I2PD18457
      title: ''
      volume_number: 2
      total_pages: 320
      base_file: v002.txt
    ee2fae60a58d488d90c22bc88e0b9505:
      image_group_id: I2PD18458
      title: ''
      volume_number: 3
      total_pages: 164
      base_file: v003.txt
    b80545732b5e45b39bbbad761e9bb90c:
      image_group_id: I2PD18459
      title: ''
      volume_number: 4
      total_pages: 392
      base_file: v004.txt
    d938e79edfb942c59758ebd521ddb036:
      image_group_id: I2PD18460
      title: ''
      volume_number: 5
      total_pages: 344
      base_file: v005.txt
    0555ffbabda2429f87f9e1df0a626015:
      image_group_id: I2PD18461
      title: ''
      volume_number: 6
      total_pages: 216
      base_file: v006.txt
    ca67d23d89aa48a1be22b587468ab3de:
      image_group_id: I2PD18462
      title: ''
      volume_number: 7
      total_pages: 356
      base_file: v007.txt
    b0e17e0ab8b441a1b236b505e6e6a4a6:
      image_group_id: I2PD18463
      title: ''
      volume_number: 8
      total_pages: 284
      base_file: v008.txt
    777de17ffff64a0085a1926e8faefa57:
      image_group_id: I2PD18464
      title: ''
      volume_number: 9
      total_pages: 257
      base_file: v009.txt
    7240b78099f5460cbd9c7f4270329cf1:
      image_group_id: I2PD18465
      title: ''
      volume_number: 10
      total_pages: 452
      base_file: v010.txt
    2e8839b95f454fe7a4d74d6d5db08a71:
      image_group_id: I2PD18466
      title: ''
      volume_number: 11
      total_pages: 392
      base_file: v011.txt
