id: IAF04FAFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T02:02:58+00:00'
last_modified: '2022-06-08T11:50:51.875789+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16581
  title: གངས་ལྗོངས་དགོན་སྡེའི་སློབ་དེབ་དཔེ་ཚོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F32F:
      image_group_id: I2PD18456
      title: ''
      total_pages: 290
      order: 1
      base_file: F32F.txt
    587C:
      image_group_id: I2PD18457
      title: ''
      total_pages: 320
      order: 2
      base_file: 587C.txt
    42D2:
      image_group_id: I2PD18458
      title: ''
      total_pages: 164
      order: 3
      base_file: 42D2.txt
    56E2:
      image_group_id: I2PD18459
      title: ''
      total_pages: 392
      order: 4
      base_file: 56E2.txt
    98EE:
      image_group_id: I2PD18460
      title: ''
      total_pages: 344
      order: 5
      base_file: 98EE.txt
    5BAA:
      image_group_id: I2PD18461
      title: ''
      total_pages: 216
      order: 6
      base_file: 5BAA.txt
    793E:
      image_group_id: I2PD18462
      title: ''
      total_pages: 356
      order: 7
      base_file: 793E.txt
    82A9:
      image_group_id: I2PD18463
      title: ''
      total_pages: 284
      order: 8
      base_file: 82A9.txt
    '4943':
      image_group_id: I2PD18464
      title: ''
      total_pages: 257
      order: 9
      base_file: 4943.txt
    1C78:
      image_group_id: I2PD18465
      title: ''
      total_pages: 452
      order: 10
      base_file: 1C78.txt
    9ABD:
      image_group_id: I2PD18466
      title: ''
      total_pages: 392
      order: 11
      base_file: 9ABD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
